// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuXyUc0_yGt0JZkqeT40cn9SU4W_RXBtI',
    appId: '1:22707297600:web:a87ed512f3d75b75666ea5',
    messagingSenderId: '22707297600',
    projectId: 'play-date-6570f',
    authDomain: 'play-date-6570f.firebaseapp.com',
    storageBucket: 'play-date-6570f.appspot.com',
    measurementId: 'G-FPTNB90S50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABdyspwICbS4Tu9m1cfRXOlLx_5jK6oVk',
    appId: '1:22707297600:android:458934323f4fc9a8666ea5',
    messagingSenderId: '22707297600',
    projectId: 'play-date-6570f',
    storageBucket: 'play-date-6570f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJrJtfngvg9FymVycskdpjAnsjGW85Z1Q',
    appId: '1:22707297600:ios:5e8da92bf856d584666ea5',
    messagingSenderId: '22707297600',
    projectId: 'play-date-6570f',
    storageBucket: 'play-date-6570f.appspot.com',
    androidClientId: '22707297600-giufc8c7lbk1d8kd0i0mm004f83evabl.apps.googleusercontent.com',
    iosClientId: '22707297600-6indjtm9m81qtuvrujkr79jm4ic92kos.apps.googleusercontent.com',
    iosBundleId: 'com.example.playDates',
  );

}